#!/bin/bash
intern=eDP-1
intern_mode=1360x768
extern=HDMI-1
extern_position=--left-of

xrandr --output "$intern" --mode $intern_mode
if xrandr | grep -q "$extern connected"; then
    xrandr --output "$extern" --auto "$extern_position" $intern
else
    xrandr --output "$extern" --off
fi

unset intern extern
